# Generated by Django 5.1.1 on 2024-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_like_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
