# Generated by Django 5.1.1 on 2024-09-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blogpost_tags_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost_tag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
