# Generated by Django 5.1.1 on 2024-09-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_blogpost_tag_tag_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='written_by',
        ),
    ]
